use_frameworks!

platform :ios, '12.1'

target 'SwiftPulseAnimation_Example' do
  pod 'SwiftPulseAnimation', :path => '../'

  target 'SwiftPulseAnimation_Tests' do
    inherit! :search_paths

    
  end
end
